# We want Exclude directives from different
# config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude

require:
  # Performance cops are bundled with Standard
  - rubocop-performance
  # Standard's config uses custom cops,
  # so it must be loaded
  - standard

inherit_gem:
  standard: config/base.yml
  # You can also choose a Ruby-version-specific config
  # standard: config/ruby-3.0.yml

inherit_from:
  - https://raw.githubusercontent.com/kspurgin/code-quality/main/configurations/rubocop/standard-override.yml

# Per project, you can enable cops (which are disabled in Standard by default)
#   here
#
# Metrics:
#   Enabled: true

# Global options, like Ruby version
AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.1
